language: python
python:
  - "2.7"
  - "3.7"

install:
  - pip install .
  - pip install pytest pytest-cov codecov

script:
  - pytest --cov-report term-missing --cov=breathe tests/

after_success:
  - codecov